Fix error caused by later versions of typescript
Error: Should not import the named export 'version' (imported as 'packageJSON') from default-exporting module (only default export is available soon)